# Generated by Django 6.0.3 on 2026-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("query", models.TextField()),
                ("response", models.TextField()),
                ("intent", models.CharField(default="general", max_length=50)),
                ("is_private", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
