# Generated by Django 5.2.11 on 2026-03-05 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=50)),
                ('current_price', models.FloatField()),
                ('change', models.FloatField(default=0)),
                ('change_percent', models.FloatField(default=0)),
                ('day_high', models.FloatField(default=0)),
                ('day_low', models.FloatField(default=0)),
                ('pe_ratio', models.FloatField(default=0)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('buying_price', models.FloatField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_stocks', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stock')),
            ],
            options={
                'db_table': 'portfolio_stocks',
                'ordering': ['sector', 'stock__symbol'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
