# Generated by Django 4.2 on 2026-03-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_stock_portfoliostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
