# Generated by Django 4.2 on 2026-03-12 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SIGNUP', 'User Signup'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('ADD_STOCK', 'Added Stock to Portfolio'), ('REMOVE_STOCK', 'Removed Stock from Portfolio'), ('VIEW_STOCKS', 'Viewed Sector Stocks'), ('VIEW_PORTFOLIO', 'Viewed Portfolio'), ('VIEW_METALS', 'Viewed Metals Prices'), ('API_ACCESS', 'Accessed API Endpoint')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_key_used', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
