# Generated by Django 6.0.2 on 2026-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_mpin_telegramotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
