# Generated by Django 6.0.2 on 2026-03-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_telegram_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_id",
        ),
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="TelegramOTP",
        ),
    ]
